CREATE TABLE tb_users ( 
id INT NOT NULL AUTO_INCREMENT, 
email VARCHAR(30) NOT NULL 
,name VARCHAR(40) NOT NULL 
,id_file INT NULL 
, password VARCHAR(20) NOT NULL 
,id_status INT NULL 
, PRIMARY KEY (id));

/* ALTER TABLE */ 

ALTER TABLE tb_users 
ADD COLUMN email VARCHAR(30) NOT NULL 
,ADD COLUMN name VARCHAR(40) NOT NULL 
,ADD COLUMN id_file INT NULL 
, ADD COLUMN password VARCHAR(20) NOT NULL 
,ADD COLUMN id_status INT NULL 
,